### ISSUE TITLE
Generalized Graphs

### ISSUE THREAD

**Issue by kowshikthopalli** [mys007/ecc#2]
Hi. Great paper and great work. I installed pytorch -0.3 in a conda environment and installed dependencies. The code runs successfully. 

I was wondering when the code for generalized graph classification shall be released?

**Comment by mys007** [comment]
Hi, I'm happy that it runs. Your question is valid and the unfortunate truth is that probably never:(. That part is still in it's original Matlab+Lua+torch7 spaghetti from late 2016 and I'm afraid it's not so relevant anymore today/too much effort to do so, sorry...
